[package]
name = "mdchat_common"
version = "0.2.0"
authors = ["Michal Douša <dousamichal0807@seznam.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
chrono = "0.4"
rand = "0.8"
sha2 = "0.10"
